name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4
      - name: Configure GPG Key
        run: |
          echo -n "$GPG" | base64 --decode | gpg --import
        env:
          GPG: ${{ secrets.GPG }}
      - name: script
        run: |
          echo 'DEBSIGN_KEYID=gamecube02+git@gmail.com' > ~/.devscripts
          sudo apt-get update -y
          sudo apt-get install -y fakeroot build-essential devscripts debhelper
          sudo apt-get install -y libcurl4-gnutls-dev subversion libsvn-perl libyaml-perl cvs cvsps libdbd-sqlite3-perl dh-exec dh-apache2 asciidoc xmlto docbook-xsl
          dget -u https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/git/1:2.51.0-1ubuntu1/git_2.51.0-1ubuntu1.dsc
          cd git-2.51.0
          echo "y" | debuild
