name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
    env: 
      DSCVERIFY_KEYRINGS: /etc/apt/trusted.gpg:~/.gnupg/pubring.kbx:~/.gnupg/trustdb.gpg
    steps:
      - uses: actions/checkout@v4
      - name: script
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential devscripts debhelper libcurl4-gnutls-dev subversion libsvn-perl libyaml-perl cvs cvsps libdbd-sqlite3-perl dh-exec dh-apache2 asciidoc xmlto docbook-xsl
          dget -u https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/git/1:2.51.0-1ubuntu1/git_2.51.0-1ubuntu1.dsc
          cd git-2.51.0
          echo "y" | debuild
